import { test, expect } from '@playwright/test';

test('zirvak bubbles in the open qazan, freezes on pause, and steams under the lid', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/locale', route => route.fulfill({ contentType: 'application/json', body: '{"locale":"en"}' }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore the kitchen first' }).click();
  await page.locator('.app-settings > summary').click();
  await page.getByRole('button', { name: 'Scripted cooking demo', exact: true }).click();
  const scene = page.locator('.canvas-host');
  await expect(scene).toHaveAttribute('data-qazan-bubbles', '0');
  await page.getByRole('button', { name: '4×', exact: true }).click();
  await page.getByRole('button', { name: /Let’s make plov/ }).click();
  await expect(scene).toHaveAttribute('data-qazan-phase', 'boiling', { timeout: 30000 });
  await page.getByRole('button', { name: 'Pause cooking', exact: false }).click();
  await page.getByRole('button', { name: 'Qazan cam', exact: true }).click();
  await page.evaluate(() => scrollTo(0, 0)); await page.waitForTimeout(700);
  expect(Number(await scene.getAttribute('data-qazan-bubbles'))).toBeGreaterThan(0);
  const time = await scene.getAttribute('data-qazan-animation-time');
  await page.waitForTimeout(350); await expect(scene).toHaveAttribute('data-qazan-animation-time', time!);
  await page.screenshot({ path: 'artifacts/zirvak-simmer-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Qazan cam', exact: true }).click();
  await page.evaluate(() => scrollTo(0, 0)); await page.waitForTimeout(700);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/zirvak-simmer-mobile.png' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(scene).toHaveAttribute('data-qazan-bubbles', '0');
  await expect(scene).toHaveAttribute('data-qazan-animation-time', '0.000');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.getByRole('button', { name: 'Keep cooking', exact: false }).click();
  await page.evaluate(() => scrollTo(0, 0));
  await expect(scene).toHaveAttribute('data-qazan-phase', 'steaming', { timeout: 20000 });
  await expect(scene).toHaveAttribute('data-qazan-bubbles', '0');
  expect(Number(await scene.getAttribute('data-qazan-steam'))).toBeGreaterThan(0);
  await expect(scene).toHaveAttribute('data-qazan-food-visible', 'false');
  await page.getByRole('button', { name: 'Pause cooking', exact: false }).click();
  await page.screenshot({ path: 'artifacts/qazan-lid-closed.png' });
  expect(errors).toEqual([]);
});
